[package]
name = "crypto-locker"
version = "0.1.0"
authors = ["Chris Steffes <c.steffes@live.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include-crypt = "0.1.1"
rpassword = "5.0"


    
